In [1]:
import pandas as pd
import dotabet
import os
from datetime import datetime
features_csv_path = r"D:\WORKSPACE\dotabet\notebooks\parse_web\betting_odds.csv"

odds = pd.read_csv(features_csv_path)

In [22]:
df = odds.dropna()
df = df[df['Match Date'] != 'LIVE']

def parse_date(d):
    try:
        d = d.replace('\r\n', ' ')
        return datetime.strptime(d, '%m/%d/%y %I:%M %p')
    except ValueError:
        return pd.NaT  # pd.NaT represents Not a Time (similar to NaN)

df['Match Date'] = df['Match Date'].apply(parse_date)
df['Match Date'] = df['Match Date'].apply(lambda x: x.strftime('%Y-%m-%d %H:%M') if pd.notna(x) else x)

In [3]:
clean_odds = r"D:\WORKSPACE\dotabet\data\top_teams\ODDS.csv"

odds = pd.read_csv(clean_odds)

In [4]:
odds

,Unnamed: 0,Date,League_Name,Team_1,Odd_1,Team_2,Odd_2,Match_Date,Win,match_id_1,Unnamed: 10,Unnamed: 11
0,2,2024-03-23 16:48,DreamLeague Season 23 - SA Qualifier (2),Boom Esports,-485,BeastCoast,+310,2024-03-23 18:00,NaN,NaN,NaN,NaN
1,3,2024-03-23 16:48,DreamLeague Season 23 - SA Qualifier (2),Heroic,-700,Midas Club,+435,2024-03-23 18:00,NaN,NaN,NaN,NaN
2,4,2024-03-25 19:05,PGL Wallachia Qualifiers - SA Qualifier (2),BeastCoast,-600,Lava,+375,2024-03-25 22:00,BeastCoast,NaN,NaN,NaN
3,5,2024-03-25 19:05,PGL Wallachia Qualifiers - SA Qualifier (2),Estar Backs,-225,Infinity Gaming,+170,2024-03-26 1:00,Estar Backs,NaN,NaN,NaN
4,6,2024-03-25 19:05,PGL Wallachia Qualifiers - SEA Qualifier (3),Yangon Galacticos,-350,Salvation Gaming,+250,2024-03-26 3:00,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
121,139,2024-04-14 1:03,Dota 2 - EPL (2),Asakura,+425,Yellow Submarine,-700,2024-04-14 17:00,NaN,NaN,NaN,NaN
122,140,2024-04-14 21:03,Dota 2 - EPL (4),Monte,+425,L1ga,-700,2024-04-15 11:00,NaN,NaN,NaN,NaN
123,141,2024-04-14 21:03,Dota 2 - EPL (4),Marsbet Team,+305,Mouz,-460,2024-04-15 14:00,NaN,NaN,NaN,NaN
124,142,2024-04-14 21:03,Dota 2 - EPL (4),Asakura,-240,B8,+180,2024-04-15 17:00,NaN,NaN,NaN,NaN
125,143,2024-04-14 21:03,Dota 2 - EPL (4),Yellow Submarine,-310,Justbetter,+225,2024-04-15 20:00,NaN,NaN,NaN,NaN

In [12]:
df.keys()

Index(['Date', 'League_Name', 'Team_1', 'Odd_1', 'Team_2', 'Odd_2',
       'Match_Date', 'Win'],
      dtype='object')

In [9]:
df

,Date,League_Name,Team_1,Odd_1,Team_2,Odd_2,Match_Date,Win
0,2024-03-23 16:48,DreamLeague Season 23 - SA Qualifier (2),Boom Esports,-485,BeastCoast,+310,2024-03-23 18:00,NaN
1,2024-03-23 16:48,DreamLeague Season 23 - SA Qualifier (2),Heroic,-700,Midas Club,+435,2024-03-23 18:00,NaN
2,2024-03-25 19:05,PGL Wallachia Qualifiers - SA Qualifier (2),BeastCoast,-600,Lava,+375,2024-03-25 22:00,BeastCoast
3,2024-03-25 19:05,PGL Wallachia Qualifiers - SA Qualifier (2),Estar Backs,-225,Infinity Gaming,+170,2024-03-26 1:00,Estar Backs
4,2024-03-25 19:05,PGL Wallachia Qualifiers - SEA Qualifier (3),Yangon Galacticos,-350,Salvation Gaming,+250,2024-03-26 3:00,NaN
...,...,...,...,...,...,...,...,...
121,2024-04-14 1:03,Dota 2 - EPL (2),Asakura,+425,Yellow Submarine,-700,2024-04-14 17:00,NaN
122,2024-04-14 21:03,Dota 2 - EPL (4),Monte,+425,L1ga,-700,2024-04-15 11:00,NaN
123,2024-04-14 21:03,Dota 2 - EPL (4),Marsbet Team,+305,Mouz,-460,2024-04-15 14:00,NaN
124,2024-04-14 21:03,Dota 2 - EPL (4),Asakura,-240,B8,+180,2024-04-15 17:00,NaN
125,2024-04-14 21:03,Dota 2 - EPL (4),Yellow Submarine,-310,Justbetter,+225,2024-04-15 20:00,NaN

In [13]:
df2 = df.drop_duplicates(subset=['Match_Date', 'Team_1', 'Team_2'], keep='first')

In [15]:
df2.to_csv(clean_odds)